apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: "1.2.1"
      helm:
        valueFiles:
          - $values/gitops/values/external-secrets-values.yaml
    - repoURL: REPLACE_ME_REPO_URL
      targetRevision: main
      ref: values
    - repoURL: REPLACE_ME_REPO_URL
      targetRevision: main
      path: gitops/platform/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
