apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: listmonk
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jluisreyvargas/listmonk2
    targetRevision: master
    path: gitops/workloads/listmonk
  destination:
    server: https://kubernetes.default.svc
    namespace: listmonk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
