apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: listmonk-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: listmonk-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: REPLACE_ME_SECRETS_MANAGER_NAME
